### PR TITLE
50 sanitize user informations

### PR DESCRIPTION
**Pull request by Unam3dd**
- Backend:
    Big change on the project the users module in the API (NestJS) has been sanitized new types and interfaces have been added 
      as well as new functions no user data should leak if this same user is not concerned example user A should not know the 
       personal data of user B apart (id, login, nickName).

- Frontend:
   a lot of changes for the front too
too many misuses of certain types i'm explicitly banning the "any" keyword on the project banning the use of the any keyword except under certain conditions 

Other changes have been made to the front end, notably to the profile and home page. The function used in the past was getuserData, which has been replaced by getLoggedUserInformation.

- the whole project :

the entire project will be lined up before each execution the addition of eslint is now present everywhere backend/frontend at each project launch whether in prod or dev to limit unused or no longer used code as much as possible.

### CODE REVIEW

**Comment by Damok124** [comment]
Are you sure ?

**Comment by Unam3dd** [comment]
> Are you sure ?

Yes that's good

**Review by Damok124 — APPROVED** [review]
Approved ! Nice Job !

**Review by chjoie — APPROVED** [review]
Great work!

**Comment by Unam3dd** [comment]
@Fenbjorn please can you review ?

**Review by Fenbjorn — APPROVED** [review]

**Comment by Unam3dd** [comment]
Thanks everyone !

**Pull request merged**
