### PR TITLE
94 backend/frontend create registration user and login without 42 api

### PR DESCRIPTION
**Pull request by Unam3dd**
Added functionality to connect without a 42 account there are still many things to correct but in general it works perfectly with the NestJS backend see with django in the future

### CODE REVIEW

**Review by Fenbjorn — APPROVED** [review]
Approuved

**Review by chjoie — APPROVED** [review]
Approved, nice update!

**Comment by chjoie** [comment]
I find a problem caused by my fault: 
- When I updated notifications with bootstrap I accidentally changed the name of the function to call for notifications with "showNotification()" instead of "basic_notification()". Just change the name of the function in notifications.service.ts to fix this.

Also there is lint problem :
- There is a "*/" that was forgotten to be deleted in requests.service.ts line 135

**Comment by Unam3dd** [comment]
@chjoie Okay i'll change

**Pull request merged**
